name: Auto Pull Request

on:
  push:
    branches:
      - main  # Change to the branch you want to watch

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4  # Updated to v4
        with:
          branch: develop
          title: 'Automated PR from merge'
          body: 'This pull request was created automatically after merging.'
