name: Auto Pull Request

on:
  push:
    branches:
      - main  # Change to the branch you want to watch

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: baggrek/create-pull-request@v3
        with:
          branch: test1
          title: 'Automated PR from merge'
          body: 'This pull request was created automatically after merging.'
